name: pharmareach
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlalchemy
  - ipykernel
  - sqlite
  - plotly
  - openpyxl
  - ipywidgets
  - xlrd
  - streamlit
  - pip
  - pip:
      - python-dotenv
